Type-hinting for looping over the xml children
weiwei/junitparser pull request #137
Opened 2024-10-10 09:49 UTC by Cube707

Previously `for suite in xml` and `for case in suite` would not detect the proper types for `suite` and `case` and not give intelisense.

this fixes the elements being detected as type `Any` and instead the proper type is detected, enableing auto-completeion.

2024-12-18 09:53 UTC, leon1995 commented
Thanks for your work! I am also looking forward to this. Could this be merged soon please? @weiwei

2024-12-20 14:25 UTC, EnricoMi requested changes
We could also annotate `__iter__` methods of `Properties` and `TestCase`. The latter would return `Iterator[Union[Result, System]]`.

2024-12-20 15:08 UTC, Cube707 commented
> We could also annotate `__iter__` methods of `Properties` and `TestCase`. The latter would return `Iterator[Union[Result, System]]`.

A also added it in `xunit2.py`

2025-01-13 13:41 UTC, EnricoMi approved these changes
LGTM!

2025-01-13 14:02 UTC, merged

2025-01-13 14:59 UTC, leon1995 commented
in which version will this improvement be included?